feat(card): add swipeable card
wdjennane/WEB2_P2021_FINAL_PROJECT pull request #29
Opened 2020-07-07 12:19 UTC by NatsuDzn

2020-07-07 15:15 UTC, ghost requested changes
Le swipe de la card fonctionne mais les `ahref` ne fonctionne plus

2020-07-07 15:17 UTC, NatsuDzn commented
> Le swipe de la card fonctionne mais les `ahref` ne fonctionne plus

J'avais remarqué ça sur Chrome 
Mais avec Firefox je n'ai pas ce problème 
Je n'ai pas pu test sur un véritable téléphone car ce n'est pas encore en master

2020-07-07 15:20 UTC, jshaows commented
Il te suffit de te connecter à l'adresse IP qui n'est pas `locahost` que react te fourni pour te accéder au site sur ton mobile

2020-07-07 15:22 UTC, ghost requested changes
Il faudrait que tu passes par une props si c'est une swipe card ou non

![Capture d’écran 2020-07-07 à 17 22 06](https://user-images.githubusercontent.com/58045704/86803609-703de580-c076-11ea-859b-e994d8e32199.png)

2020-07-07 15:26 UTC, NatsuDzn commented
> Il faudrait que tu passes par une props si c'est une swipe card ou non
> 
> ![Capture d’écran 2020-07-07 à 17 22 06](https://user-images.githubusercontent.com/58045704/86803609-703de580-c076-11ea-859b-e994d8e32199.png)

Pour la box shadow ?

2020-07-07 15:28 UTC, jshaows commented
Oui et pour le `padding`

2020-07-07 15:35 UTC, NatsuDzn commented
> Oui et pour le `padding`

Je viens de fix le problème par rapport au style je vais voir pour les boutons

2020-07-08 06:58 UTC, ghost approved these changes

2020-07-08 06:59 UTC, merged